### ISSUE TITLE
Clean up the inventory files herein

### ISSUE THREAD

**Issue by dougbtv** [redhat-nfvpe/base-infra-bootstrap#26]
There's some confusion about how to use them, there's too many and they're named poorly.

**Comment by s1061123** [comment]
I am rewriting inventory file and current draft is following:

- changing it to yaml file
- add all group_vars in the file (it's simple to handle)

Comments are appreciated.
```
# Setup this host first, and put the IP here.
all:
  hosts:
    virt_host:
      ansible_host:  <IP ADDR>
      ansible_user: root

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    vm_disk_device: vdb

virthosts:
  hosts:
    virt_host
  vars:
    virtual_machines:
      - name: openshift-master
        node_type: master
        system_ram_mb: 24576
        system_cpus: 4
(snip)
      - name: openshift-node-2
        node_type: nodes
        system_ram_mb: 24576
        system_cpus: 4
    centos_genericcloud_url: http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1801-01.qcow2
(snip)
    increase_root_size_gigs: 35
```
